pipeline:

    build-branch:
        image: plugins/docker
        repo: scienta/brandr-app
        dockerfile: Dockerfile
        context: ./
        auto_tag: false
        tags: "branch-${DRONE_BRANCH}"
        build_args:
            - APP_VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
        secrets: [ docker_username, docker_password ]
        when:
            event: [push]

    build-tag:
        image: plugins/docker
        repo: scienta/brandr-app
        dockerfile: Dockerfile
        context: ./
        auto_tag: false
        tags: "${DRONE_TAG}"
        build_args:
            - APP_VERSION=${DRONE_TAG}
        secrets: [ docker_username, docker_password ]
        when:
            event: [tag]
