pipeline:
    restore-cache:
        image: drillster/drone-volume-cache
        restore: true
        mount:
            - /drone/docker-brandr-app
        volumes:
            - /tmp/cache:/cache

    build-branch:
        image: plugins/docker
        repo: scienta/brandr-app
        dockerfile: Dockerfile
        context: ./
        auto_tag: false
        tags: "branch-${DRONE_BRANCH}"
        build_args:
            - APP_VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
        storage_path: /drone/docker-brandr-app
        secrets: [ docker_username, docker_password ]
        when:
            event: [push]

    build-tag:
        image: plugins/docker
        repo: scienta/brandr-app
        dockerfile: Dockerfile
        context: ./
        auto_tag: false
        tags: "${DRONE_TAG}"
        build_args:
            - APP_VERSION=${DRONE_BRANCH}
        storage_path: /drone/docker-brandr-app
        secrets: [ docker_username, docker_password ]
        when:
            event: [tag]

    rebuild-cache:
        image: drillster/drone-volume-cache
        rebuild: true
        mount:
            - /drone/docker-ids
        volumes:
            - /tmp/cache:/cache
