version: '3.2'
services:
  brandr-app:
    container_name: brandr-app
    image: scienta/brandr-app:latest
    restart: always
    ports:
      - "${BIND_INTERFACE}:8080:80"
    environment:
      - API_ENDPOINT=${API_ENDPOINT}
  brandr-api:
    container_name: brandr-api
    image: scienta/brandr-api:1.4.2
    restart: always
    working_dir: /app
    ports:
      - "${BIND_INTERFACE}:9080:3000"
    environment:
      - NODE_ENV=dev
      - API_ENDPOINT=${API_ENDPOINT}
      - DEBUG=*,-navigator:info,-sequelize*,-koa*,-nodemon*,-snapdragon*,-puppeteer*
