version: '3.2'
services:
  brandr-app:
    container_name: brandr-app
    build:
        context: .
        args:
            APP_VERSION: 'dev'
    restart: always
    ports:
      - "${BIND_INTERFACE}:8080:80"
    environment:
      - API_ENDPOINT=${API_ENDPOINT}
