version: '3.2'
services:
  brandr-app:
    container_name: brandr-app
    image: scienta/brandr-app:1.3.1
    restart: always
    ports:
      - "${BIND_INTERFACE}:8080:80"
    environment:
      - API_ENDPOINT=${API_ENDPOINT}
    command: /bin/sh -c "envsubst '$${API_ENDPOINT}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  brandr-api:
    container_name: brandr-api
    image: scienta/brandr-api:1.3.2
    restart: always
    working_dir: /app
    ports:
      - "${BIND_INTERFACE}:9080:3000"
    environment:
      - NODE_ENV=dev
      - API_ENDPOINT=${API_ENDPOINT}
      - DEBUG=*,-navigator:info,-sequelize*,-koa*,-nodemon*,-snapdragon*,-puppeteer*
    command: nodemon /app/index.js
